package com.wadii.router

enum class Route {
    LOGIN, REGISTER,
    HOME, SEARCH, ORDERS, NEW_ORDER, ORDER_DETAIL, SAVED_OFFERS, PROVIDER_DETAIL,
    CHAT,
    NOTIFICATIONS, PROFILE,
    PROVIDER_DASHBOARD, PROVIDER_ORDERS, RESPOND_ORDER, PROVIDER_OFFERS,
    ADMIN_DASHBOARD, PROVIDER_REQUESTS, ADVERTISEMENTS, SERVICES
}
